
// This file is generated by Firebase Genkit.
'use server';
/**
 * @fileOverview Analyzes stock market trends and provides investment recommendations.
 *
 * - analyzeStockTrend - Analyzes the trend of a given stock.
 * - AnalyzeStockTrendInput - The input type for the analyzeStockTrend function.
 * - AnalyzeStockTrendOutput - The return type for the analyzeStockTrend function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeStockTrendInputSchema = z.object({
  tickerSymbol: z.string().describe('The ticker symbol of the stock to analyze.'),
  chartDataUri: z
    .string()
    .describe(
      "A candlestick chart of the stock, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'. This will be ignored by the AI."
    ),
});
export type AnalyzeStockTrendInput = z.infer<typeof AnalyzeStockTrendInputSchema>;

const AnalyzeStockTrendOutputSchema = z.object({
  analysis: z.string().describe('The AI-generated general market analysis and outlook for the stock.'),
  recommendation: z.string().describe('Investment recommendations based on the general analysis.'),
});
export type AnalyzeStockTrendOutput = z.infer<typeof AnalyzeStockTrendOutputSchema>;

export async function analyzeStockTrend(input: AnalyzeStockTrendInput): Promise<AnalyzeStockTrendOutput> {
  return analyzeStockTrendFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeStockTrendPrompt',
  input: {schema: AnalyzeStockTrendInputSchema},
  output: {schema: AnalyzeStockTrendOutputSchema},
  prompt: `You are an expert stock market analyst.
You will be provided with a stock ticker symbol: {{{tickerSymbol}}}.

Your task is to:
1.  Provide a general market analysis and outlook for the stock: {{{tickerSymbol}}}. This analysis should be based *solely* on your broader knowledge of the company, its sector, relevant economic factors, and recent news.
2.  **Important: Do NOT analyze, reference, or base any part of your response on any image or chart data (like the one at '{{media url=chartDataUri}}'). Your analysis must come from your general knowledge only.**
3.  Based on this general knowledge and market outlook, offer investment recommendations for {{{tickerSymbol}}}.

Your response must populate the 'analysis' and 'recommendation' fields according to the defined output structure.
The 'analysis' field should contain your general market analysis and outlook (ignoring any images).
The 'recommendation' field should contain your investment advice (ignoring any images).`,
});

const analyzeStockTrendFlow = ai.defineFlow(
  {
    name: 'analyzeStockTrendFlow',
    inputSchema: AnalyzeStockTrendInputSchema,
    outputSchema: AnalyzeStockTrendOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error('The AI model did not return a valid output.');
    }
    return output;
  }
);

