
// This file is generated by Firebase Genkit.
'use server';
/**
 * @fileOverview Analyzes stock market trends using candlestick charts and provides investment recommendations.
 *
 * - analyzeStockTrend - Analyzes the trend of a given stock.
 * - AnalyzeStockTrendInput - The input type for the analyzeStockTrend function.
 * - AnalyzeStockTrendOutput - The return type for the analyzeStockTrend function.
 */

import {ai} from '@/ai/genkit';
import {z} from 'genkit';

const AnalyzeStockTrendInputSchema = z.object({
  tickerSymbol: z.string().describe('The ticker symbol of the stock to analyze.'),
  chartDataUri: z
    .string()
    .describe(
      "A candlestick chart of the stock, as a data URI that must include a MIME type and use Base64 encoding. Expected format: 'data:<mimetype>;base64,<encoded_data>'."
    ),
});
export type AnalyzeStockTrendInput = z.infer<typeof AnalyzeStockTrendInputSchema>;

const AnalyzeStockTrendOutputSchema = z.object({
  analysis: z.string().describe('The AI analysis of the candlestick chart (or general market analysis if chart is a placeholder).'),
  recommendation: z.string().describe('Investment recommendations based on the analysis.'),
});
export type AnalyzeStockTrendOutput = z.infer<typeof AnalyzeStockTrendOutputSchema>;

export async function analyzeStockTrend(input: AnalyzeStockTrendInput): Promise<AnalyzeStockTrendOutput> {
  return analyzeStockTrendFlow(input);
}

const prompt = ai.definePrompt({
  name: 'analyzeStockTrendPrompt',
  input: {schema: AnalyzeStockTrendInputSchema},
  output: {schema: AnalyzeStockTrendOutputSchema},
  prompt: `You are an expert stock market analyst.
The user requests an analysis for the stock {{{tickerSymbol}}}, treating the provided image as its current candlestick chart, as if from Google Finance.

Provided chart image:
{{media url=chartDataUri}}

Perform the following:
1.  Carefully examine the provided image.
2.  If the image is a detailed candlestick chart:
    a.  Provide a thorough technical analysis, identifying key trends, patterns (e.g., head and shoulders, support/resistance levels), and indicators.
    b.  Based on this technical analysis, offer specific, actionable investment recommendations (e.g., buy, sell, hold, price targets, stop-loss levels).
3.  If the image appears to be a placeholder (e.g., it primarily contains text like '{{{tickerSymbol}}} Chart' or shows no actual chart data):
    a.  Acknowledge that a detailed chart image was not available for a full technical analysis.
    b.  Provide a general market analysis and outlook for {{{tickerSymbol}}} based on your broader knowledge of the company, its sector, and recent news.
    c.  Offer general investment considerations or recommendations for {{{tickerSymbol}}} based on this general outlook, highlighting that this is not based on a detailed chart reading.

Your response must populate the 'analysis' and 'recommendation' fields according to the defined output structure.
The 'analysis' field should contain your detailed findings (either technical or general, depending on the image).
The 'recommendation' field should contain your investment advice.`,
});

const analyzeStockTrendFlow = ai.defineFlow(
  {
    name: 'analyzeStockTrendFlow',
    inputSchema: AnalyzeStockTrendInputSchema,
    outputSchema: AnalyzeStockTrendOutputSchema,
  },
  async input => {
    const {output} = await prompt(input);
    if (!output) {
      throw new Error('The AI model did not return a valid output.');
    }
    return output;
  }
);

